// VI SKAL IGEN REQUIRE EXPRESS
const express = require('express');
// WE CAN NOW CALL ROUTER AND CALL IT AS A FUNCTION
// WE CAN THEN CREATE OUR OWN ROUTES IN SEPERATE FILES AND IMPORT IT INTO THE MAIN .JS FILE
const router = express.Router();

// WE IMPORT THE MODEL WE WANT TO POST TO
const Post = require('../Models/Post');

// YOU NOW HAVE THE ABILITY TO CREATE ROUTES
//ROUTES - 'GET' MEANS THAT SHOOTS US BACK A MESSAGE. IF WE WOULD WANT TO SEND A MESSAGE LIKE A 
// LOGIN FORM, THEN WE WOULD USE 'POST'. IF WE HAVE A POST LIST AND WANT TO DELETE A POST, WE CAN USE 'DELETE.
// WE WOULD USE PATCH FOR UPDATING
// '/' IS THE ROUTE WE WANT TO GO TO
router.get('/', (req, res) => {
    res.send('We are on posts');
});

// WE HAVE TO ACCESS THE INFORMATION, THE THING THAT WE'RE POSTING TO OUR API
// FROM THE BODY, SO request.body
router.post('/', (req, res) => {
    console.log(req.body);
})

// WE SET THIS EQUAL TO ROUTER SO THAT WE EXPORT THE WHOLE ROUTER
module.exports = router;